name: 'AWS Copilot Deploy'
description: 'Deploy Docker Image to AWS Fargate by AWS Copilot'
inputs:
  svc:
    description: 'Your Service Name'
    required: true
  tag:
    description: 'Container Image Tag'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.svc }}
    - ${{ inputs.tag }}